### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [DatanoiseTV/RP2040-DSP-FreeRTOS-Template#1]
Hello!

I found your project from https://hackaday.com/2022/06/21/a-simple-rp2040-based-audio-dsp-board/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code, PCB files and images in any purpose?
It would be great to see any popular open source license.

**Comment by DatanoiseTV** [comment]
I have added LICENSE.md. It is licensed under the MIT License.

**Comment by vazhnov** [comment]
MIT — great! Thank you!
